### ISSUE TITLE
iPad Air 2 J82AP

### ISSUE THREAD

**Issue by CloneBoy83** [Siguza/cl0ver#67] opened 2018-08-13 20:08 UTC
Hello my friend, i don't have find an offset for my device, hope you can help me.

Here are the log files from my device

Log from Terminal
https://pastebin.com/CfQfDHpA

Panic-Log
https://pastebin.com/26PYcasq

Thank you very much

**Comment by Siguza** [comment] 2018-08-15 15:15
Closing this as duplicate of #66, please try the solution posted there.

**Closed by Siguza** 2018-08-15 15:15 UTC
