### ISSUE TITLE
Unsupported device: iPad Air 2 (J82AP) / iOS 9.0.2 (13A452)

### ISSUE THREAD

**Issue by NeoMan-Hx** [Siguza/cl0ver#21] opened 2017-02-03 18:49 UTC
I use the 1.0.2 version of cl0ver, still prompt [!] Unhandled error: Unsupported device/OS combination [src/lib/offsets.c:51 reg_anchor], my device is iPad5,4, ios 9.0.2 pangujb

```
[*]Checkingfor config file... [src/lib/offsets.c:120 off_cfg]
[*] Nope, let's hope the registry has a compatible anchor & vtab... [src/lib/offsets.c:124 off_cfg]
[*] Page size: 0x0000000000004000 [src/lib/uaf_rop.c:113 uaf_rop_stack]
[*] Allocating ROP stack page at 0x000000000c000000 [src/lib/uaf_rop.c:117 uaf_rop_stack]
[*] Allocated ROP page at 0x000000000c000000 [src/lib/uaf_rop.c:123 uaf_rop_stack]
[*] Initializing offsets... [src/lib/offsets.c:160 off_init]
[*] Checking for offsets cache file... [src/lib/offsets.c:173 off_init]
[*] Using info leak to get kernel slide... [src/lib/slide.c:64 get_kernel_slide]
[*] Dict: [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[0]: 0x000000d3 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[1]: 0x81000002 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[2]: 0x08000004 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[3]: 0x006c6f6c [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[4]: 0x84000400 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[5]: 0x69696969 [src/lib/slide.c:33 get_kernel_anchor]
[*] dict[6]: 0x69696969 [src/lib/slide.c:33 get_kernel_anchor]
[*] Spawning user client / Parsing dictionary... [src/lib/io.c:59 _io_spawn_client]
[*] Getting IO service handle... [src/lib/io.c:45 _io_get_service]
[*] Getting IO master port... [src/lib/io.c:30 get_io_master_port]
[*] Creating dict iterator... [src/lib/io.c:72 _io_iterator]
[*] Getting next element from iterator... [src/lib/io.c:84 _io_next]
[*] Releasing user client... [src/lib/io.c:131 _io_release_client]
[*] Kernel stack: [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 0]: 0x6969696969696969 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 1]: 0xffffff802394a000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 2]: 0x00000000ff002bf1 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 3]: 0xffffff8002b885cc [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 4]: 0xffffff80041b99b4 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 5]: 0xffffff8002cd8900 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 6]: 0xffffff8002b885a0 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 7]: 0xffffff8020573950 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 8]: 0xffffff80234d4edc [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[ 9]: 0x0000000000000000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[10]: 0xffffff8023950a50 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[11]: 0xffffff8002b88000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[12]: 0xffffff802399ecc8 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[13]: 0x0000000000001074 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[14]: 0x0000000000000000 [src/lib/slide.c:44 get_kernel_anchor]
[*] buf[15]: 0xffffff802399e050 [src/lib/slide.c:44 get_kernel_anchor]
[*] Getting anchor address from registry... [src/lib/offsets.c:25 reg_anchor]
[*] Model: J82AP [src/lib/device.c:34 get_model_internal]
[*] OS build: 13A452 [src/lib/device.c:102 get_os_version_internal]
[!] Unhandled error: Unsupported device/OS combination [src/lib/offsets.c:51 reg_anchor]
```

Please forgive my first language is not English

Thank you!
[panic-2016-06-02-131123.txt](https://github.com/Siguza/cl0ver/files/751345/panic-2016-06-02-131123.txt)

**Comment by Siguza** [comment] 2017-02-12 17:20
This is a duplicate of issue #17, so I'm closing this. Your input is quite valuable though, please see [my last comment on issue 17](https://github.com/Siguza/cl0ver/issues/17#issuecomment-279233102).

**Closed by Siguza** 2017-02-12 17:20 UTC
