### ISSUE TITLE
My device is not supported yet N71AP 9.0.1

### ISSUE THREAD

**Issue by eramirez3** [Siguza/cl0ver#40] opened 2017-02-22 10:43 UTC
I already have the log after panic, but where I find the  saved output ?

**Comment by leandroprz** [comment] 2017-02-22 13:11
Have you tried using the [9.0.2 offsets.dat](https://github.com/Siguza/cl0ver/tree/master/offsets)? It might work with that.

**Comment by eramirez3** [comment] 2017-02-22 15:13
Yep, but it didn't worked

**Comment by Siguza** [comment] 2017-02-22 16:12
Marking this as duplicate of #41.

**Closed by Siguza** 2017-02-22 16:12 UTC
